Repository yiisoft/yii2-bootstrap4, pull requests merged in 2019-06, with the labels that each got.

#141 aria-expanded should not be set with boolean in yii\bootstrap4\Accordion
  CHANGELOG.md
  src/Accordion.php
  tests/AccordionTest.php
Labels: type:bug

#144 Passing active status to Dropdown from Nav/isItemActive to fix #133
  CHANGELOG.md
  UPGRADE.md
  composer.json
  src/Dropdown.php
  src/Nav.php
  src/Tabs.php
  tests/DropdownTest.php
  tests/NavTest.php
  tests/TestCase.php
Labels: status:code review

#145 Update example in doc to Bootstrap 4
  src/ActiveField.php
Labels: type:docs

#149 Fix ButtonGroup example
  src/ButtonToolbar.php
Labels: type:docs
