Repository yiisoft/yii2-bootstrap4, pull requests merged in 2019-02, with the labels that each got.

#104 Fix tests running on Yii 2.0.16
  tests/ActiveFieldTest.php
  tests/ActiveFormTest.php
Labels: type:test

#109 Fix Tabs::$encodeLabel that wasn't taken into account
  CHANGELOG.md
  src/Tabs.php
  tests/TabsTest.php
Labels: type:bug

#112 fixed #111
  src/Modal.php
Labels: type:docs
