Repository yiisoft/yii2-bootstrap4, pull requests merged in 2019-05, with the labels that each got.

#130 Add the constant of the extra large modal
  CHANGELOG.md
  src/Modal.php
Labels: status:ready for merge

#134 Added "tablist" role
  CHANGELOG.md
  src/Tabs.php
  tests/TabsTest.php
Labels: type:bug

#137 Added disabled option for Nav, Dropdown and Tabs
  CHANGELOG.md
  src/Dropdown.php
  src/Nav.php
  src/Tabs.php
  tests/DropdownTest.php
  tests/NavTest.php
  tests/TabsTest.php
Labels: type:enhancement

#139 Parent li should not contain active class. Fixes #135
  CHANGELOG.md
  src/Nav.php
  src/Tabs.php
  tests/TabsTest.php
Labels: status:ready for merge, type:bug
